# Message sent to the player when a tracker is applied
tracker_add_message: "&7&l[&d&lSakura&b&lMC&7&l] &aTracker added successfully!"

# Message sent to the player when trying to apply a tracker to an item that already has that tracker equipped
tracker_already_equipped_message: "&7&l[&d&lSakura&b&lMC&7&l] &cThis item already has this tracker equipped!"

# Message sent to the player when trying to equip a tracker to an item that it doesn't support
tracker_invalid_item_message: "&7&l[&d&lSakura&b&lMC&7&l] &cThis tracker can't be applied to this item."